name: CI Runer
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checlkout@v1
      - name: Use Nodejs 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache Npm depencies
        uses: actions/cache@v1
      - name: Install Dependence
      run: |
          npm install -g yarn
          yarn --frozen-lockfile --non-interactive
      - name: Build
        run: yarn build
        env:
          CI: true