name: CI Runer
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Nodejs 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependence
        run: |
          npm install -g yarn
          yarn --frozen-lockfile --non-interactive
      - name: Build
        run: yarn build
        env:
          CI: true
      - name: Deploy
        uses: peaeiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.MY_BLOG_TOKEN}}
          publish_dir: ./public
